version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: filp/whoops
    versions:
    - 2.10.0
    - 2.11.0
    - 2.12.0
    - 2.9.2
  - dependency-name: symfony/http-foundation
    versions:
    - 4.4.19
  - dependency-name: phpunit/phpunit
    versions:
    - 8.5.14
  - dependency-name: mockery/mockery
    versions:
    - 1.3.3
